//! T040 — trybuild harness for SC-004 (subject-type compile-time
//! isolation). Drives the four `tests/ui/*.rs` fixtures through
//! `trybuild::TestCases::compile_fail` and asserts that each one fails
//! to compile. The fixtures live in `tests/ui/` (see T036-T039).
//!
//! ## Why four fixtures, not one
//!
//! The type fence is two-layer per research R8:
//!   - **Inner `Sub` newtype is `pub(in crate::auth)`** — outside `auth`,
//!     neither `VaultSubject::new` nor `AdminSubject::new` is callable,
//!     and neither `.0` field is reachable.
//!   - **Each subject's `FromRequestParts` reads a typed extension key**
//!     that only the matching guard inserts.
//!
//! Each fixture exercises one defeat path that a developer might
//! plausibly try:
//!   1. `wrong_subject_in_vault_handler.rs` — funnel an `AdminSubject`
//!      into a vault-only logic path by re-wrapping it as a
//!      `VaultSubject`. Fails because `VaultSubject::new` is private.
//!   2. `wrong_subject_in_admin_handler.rs` — mirror of (1).
//!   3. `attempted_from_impl_vault_to_admin.rs` — declare
//!      `impl From<VaultSubject> for AdminSubject`. Fails because the
//!      inner `Sub` field is private (destructure barrier) AND the
//!      tuple-struct constructor leaks the private `Sub` type.
//!   4. `attempted_shared_trait_method.rs` — declare a shared trait
//!      whose method returns `&str`, implement for both subjects. Fails
//!      because the only accessor (`into_string`) consumes the wrapper,
//!      forcing the impl to reach the private inner `Sub` field.
//!
//! If a fixture starts compiling cleanly (e.g., after a privacy
//! relaxation in `auth/subject.rs`), trybuild reports the SC-004
//! guarantee as broken and this test fails. The intent is that any
//! future PR weakening the type fence MUST also delete the
//! corresponding fixture, making the privacy contract reviewable.
//!
//! ## Stderr goldens
//!
//! Goldens are generated by running `TRYBUILD=overwrite cargo test
//! --features test-utils --test subject_isolation` once, then checked
//! in alongside the `.rs` fixtures under `tests/ui/`. The `[..]`
//! wildcard pattern is used to absorb rustc-version-specific diagnostic
//! noise; only the salient phrase (e.g. `private`, `cannot construct`)
//! is anchored.

#[test]
fn subject_isolation_fixtures_fail_to_compile() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/ui/wrong_subject_in_vault_handler.rs");
    t.compile_fail("tests/ui/wrong_subject_in_admin_handler.rs");
    t.compile_fail("tests/ui/attempted_from_impl_vault_to_admin.rs");
    t.compile_fail("tests/ui/attempted_shared_trait_method.rs");
}
